//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEscrime
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class escrimeEntities : DbContext
    {
        public escrimeEntities()
            : base("name=escrimeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adherent> Adherents { get; set; }
        public virtual DbSet<arme> armes { get; set; }
        public virtual DbSet<Club> Clubs { get; set; }
        public virtual DbSet<Competition> Competitions { get; set; }
        public virtual DbSet<MaitreArme> MaitreArmes { get; set; }
        public virtual DbSet<Participer> Participers { get; set; }
    }
}
